### ISSUE TITLE
So-called full-history repo josephwright/tex-ini-files is 404

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/tex-ini-files#1]
From README, it says that
> A full history of this bundle is available from https://github.com/josephwright/tex-ini-files

But repo https://github.com/josephwright/tex-ini-files no longer exists and returns 404. So, does the current latex3/tex-ini-files repo already contain the full history?

**Comment by davidcarlisle** [comment]
@muzimuzhi  yes the git repository wasn't changed, just the github owner moved to be under latex3. We'll fix the readme to give the correct location thanks.

**Comment by muzimuzhi** [comment]
Thanks.
